baseURL = "https://engelsystem.de/doc/"
languageCode = "en-us"
title = "Engelsystem Documentation"
theme = "learn"

[params]
themeVariant = "blue"
editURL = "https://github.com/engelsystem/engelsystem-doc/tree/master/content"

[outputs]
home = [ "HTML", "RSS", "JSON"]

